[package]
name = "hello"
version = "0.1.0"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2018"

[dependencies]
# rocket = "0.5.0-dev"
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "3a7559e", default-features = false }
